# Generated by Django 2.2.6 on 2019-11-23 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='Comments',
        ),
        migrations.AddField(
            model_name='discussion',
            name='Comments',
            field=models.ManyToManyField(to='main.Comment'),
        ),
    ]
