# Generated by Django 2.2.6 on 2019-11-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191123_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Discussion'),
            preserve_default=False,
        ),
    ]
